
command -v vg >/dev/null 2>&1 && eval "$(vg eval --shell zsh)"

PROMPT='
%F{magenta}%n@%m%f %F{blue}[%~]%f
%B%(!.#.%(?.λ.%F{red}λ%f))%b '

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export CLICOLOR=1

export EDITOR="code -w"

# alias ls='ls --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias go-dorothea="ssh todd@dorothea.dropline.net"
