# Import oh-my-zsh config, if found
if [[ -r "$HOME/.zshrc.omz" ]]; then
  source "$HOME/.zshrc.omz"
fi

# Preferred editor and prompt for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='emacs'
  PROMPT='
%F{magenta}%n@%m%f %F{blue}[%~]%f
%B%(!.#.%(?.λ.%F{red}λ%f))%b '
else
  export EDITOR='code -w'
  PROMPT='
%F{blue}[%~]%f
%B%(!.#.%(?.λ.%F{red}λ%f))%b '
fi

# Colorize GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
export CLICOLOR=1

# Doesn't work with BSD ls
# alias ls='ls --color=auto' 

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias go-dorothea="ssh todd@dorothea.dropline.net"

# Import local config, if found
if [[ -r "$HOME/.zshrc.local" ]]; then
  source "$HOME/.zshrc.local"
fi
